-- Players Table
CREATE TABLE Players (
  PLAYER_ID TEXT PRIMARY KEY,
  PLAYER_NAME TEXT NOT NULL,
  DATE_OF_BIRTH DATE NOT NULL,
  GENDER TEXT NOT NULL CHECK (GENDER IN ('M', 'F')),
  DATE_SIGNED_UP DATE NOT NULL
);

-- Teams Table
CREATE TABLE Teams (
  TEAM_NAME TEXT PRIMARY KEY,
  TEAM_LOCATION TEXT NOT NULL,
  TEAM_MANAGER TEXT NOT NULL
);

-- Contracts Table
CREATE TABLE Contracts (
  CONTRACT_ID TEXT PRIMARY KEY,
  PLAYER_ID TEXT NOT NULL REFERENCES Players(PLAYER_ID),
  CURRENT_TEAM TEXT NOT NULL REFERENCES Teams(TEAM_NAME),
  SALARY REAL NOT NULL,
  START_OF_CONTRACT DATE NOT NULL,
  CONTRACT_DURATION INTEGER NOT NULL,
  COMMISSION REAL NOT NULL CHECK (COMMISSION BETWEEN 0 AND 100)
);
